### ISSUE TITLE
inconsistency with comparisons

### ISSUE THREAD

**Issue by elgbar** [Skript-Atom/Language-Skript#10]
As you can see there are some inconsistencies with the comparisons in terms of colour
![image](https://cloud.githubusercontent.com/assets/1556738/12831415/6f486ee2-cb94-11e5-8b22-087363a8ec54.png)

[click here for all comparisons](https://www.skunity.com/search?search=greater)

**Comment by tim740** [comment]
Fixed in v1.8.4 released tomorrow.
