### ISSUE TITLE
cow not an entity

### ISSUE THREAD

**Issue by elgbar** [Skript-Atom/Language-Skript#11]
Cow is not the same color as the rest of the entities/animals
![image](https://cloud.githubusercontent.com/assets/1556738/12831641/a292c92c-cb95-11e5-8bff-fb4f4623e782.png)

**Comment by tim740** [comment]
ill add it quickly

**Comment by tim740** [comment]
Fixed in v1.8.4, v1.8.4 will be released tomorrow so more bug reports would be great
