### ISSUE TITLE
Vertical is not included in the directions

### ISSUE THREAD

**Issue by elgbar** [Skript-Atom/Language-Skript#15]
![image](https://cloud.githubusercontent.com/assets/1556738/13793783/f0a8d084-eaf8-11e5-8e4c-3db854038abf.png)

**Comment by elgbar** [comment]
Language Version: 1.9.0
(ThemesName) Version: 2.1.1

**Comment by tim740** [comment]
Fixed in v1.9.1 language, releasing it later today.
