### ISSUE TITLE
Change color of commands

### ISSUE THREAD

**Issue by elgbar** [Skript-Atom/Language-Skript#17]
When you create a command it will be the default color (eg gray)
![image](https://cloud.githubusercontent.com/assets/1556738/14210428/340a87cc-f829-11e5-83f5-b6408e015733.png)
But when the name of the command is a word that is the make-the-word-a-color list the command look weird
![image](https://cloud.githubusercontent.com/assets/1556738/14210459/5d9fa9be-f829-11e5-8d6b-a8ad5ec5c106.png)
![image](https://cloud.githubusercontent.com/assets/1556738/14210461/62ab38c4-f829-11e5-8f99-aa138c0808ee.png)

Therefore was I thinking that you should set the text after the slash (/) or the word command to a fixed color to something like this:
![gma](https://cloud.githubusercontent.com/assets/1556738/14210690/6ebe4a24-f82a-11e5-892d-4d1bb012b52a.png)

**Comment by tim740** [comment]
Added in v1.9.8
