### ISSUE TITLE
Quotes some times think all the text after it is within quotes

### ISSUE THREAD

**Issue by bigfoott** [Skript-Atom/Language-Skript#2]
In this screenshot, there is a quote that is paired with another:

![](http://i.imgur.com/jBiVKTI.png)

However, when this quote exists, it thinks all the text after is is within the bounds of that quote. If I remove that quote (like I did in this screenshot):

![](http://i.imgur.com/sA7QedZ.png)

The text after it is normal

NOTE: This doesn't always happen, but most of the time it happens when percents (%) are involved.

**Comment by tim740** [comment]
Know bug thats why in 0.98.0 (just release) they are disabled in vars

**Comment by tim740** [comment]
Also you aren't using the theme

**Comment by bigfoott** [comment]
I was, but I had some tab problems so I disabled it to see if it fixed it (it didnt). It happened in the theme as well.
