### ISSUE TITLE
% Colour Formatting Doesn't Stop After The Second %

### ISSUE THREAD

**Issue by LamboCreeper** [Skript-Atom/Language-Skript#3]
In this image:

![Example](https://gyazo.com/3a20d3f670268f792f966120ff7f8066.png)

'from url' is also in blue - which it shouldn't.

Language Version: 0.96.0
Theme Version: 1.8.0
Atom Version: 1.3.1 Mac

**Comment by tim740** [comment]
I need the language and theme versions

**Comment by LamboCreeper** [comment]
0.96.0

**Comment by tim740** [comment]
Your language is out of date, please update it
