### ISSUE TITLE
WildSk - setting yaml file values

### ISSUE THREAD

**Issue by ghost** [Skript-Atom/Language-Skript#5]
the colouring goes a little messed up when u have %% and then something inside such as %player's displayname% within WildSk's  (set|put) %text% (to|in) %text% (in|to) [(yaml|yml)] [file] %text%
![screen shot 2015-12-13 at 11 42 01](https://cloud.githubusercontent.com/assets/11574824/11766804/cc347162-a18e-11e5-8b62-bdd9709a0a1d.png)

Language Version: 0.96.0
Theme Version: 1.7.0
Atom Version: 1.3.0

**Comment by tim740** [comment]
Your not using the theme
Please provide versions like i do here
#4

**Comment by tim740** [comment]
Please provide versions like i do here
https://github.com/Skript-Atom/Language-Skript/issues/4

**Comment by LuckyBowers** [comment]
fixed incorrect formatting of post ;)

**Comment by tim740** [comment]
Your using an outdated Theme and Language, please update them
