### ISSUE TITLE
Comments after an important comment

### ISSUE THREAD

**Issue by elgbar** [Skript-Atom/Language-Skript#8]
So I was adding some comments and noticed this:

![foo2-1](https://cloud.githubusercontent.com/assets/1556738/12157348/91b857d2-b4d1-11e5-937b-5fa8ff89f68b.PNG)

Comments after an important comment become, as far as I can see, normal text. 

Language Version: 1.4.0
skript-dark Version: 2.1.1

**Comment by tim740** [comment]
Thanks for this report i will fix this in the next version.

**Comment by tim740** [comment]
Fixed in v1.5.0

**Comment by tim740** [comment]
https://github.com/Skript-Atom/Language-Skript/releases/tag/v1.5.0
