### ISSUE TITLE
Bug with important comment still not fixed properly

### ISSUE THREAD

**Issue by elgbar** [Skript-Atom/Language-Skript#9]
![foo3-1](https://cloud.githubusercontent.com/assets/1556738/12183763/2bfc5c3e-b591-11e5-9606-b8020a68b711.PNG)
If the end of an important comment is placed wrongly _(like #!)_ it's the same issue ([link](https://github.com/Skript-Atom/Language-Skript/issues/8))
but if you place it the right way the last # becomes commented style

Language Version: 1.6.0
skript-dark Version: 2.1.1

**Comment by tim740** [comment]
It has to be that way, thats the way I aimed for,  if I had that last # colored it wouldn't color the rest.

**Comment by tim740** [comment]
You shouldn't be using the top one, its not designed to work like that
It was designed to work like "#!Text!# hello"
